version: "3.8"

services:
  frontend:
    container_name: react-app
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Avoid overwriting node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./frontend/.env
    depends_on:
      - task_service
    command: npm run dev -- --host
  task_service:
    build: ./task_service
    ports:
      - "8000:8000"
    volumes:
      - ./task_service:/app  # Mount task_service source code to container
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - ./task_service/.env
    depends_on:
      - mongodb
      - auth_service
    restart: always
  auth_service:
    build: ./auth_service
    ports:
      - "8001:8001"
    volumes:
      - ./auth_service:/app
    environment:
      - PYTHONUNBUFFERED=1

    depends_on:
      - mongodb
    restart: always
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: