version: "3.8"

services:
  frontend:
    container_name: react-app
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Avoid overwriting node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev -- --host
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app  # Mount backend source code to container
    environment:
      - PYTHONUNBUFFERED=1
    restart: always