version: "3.8"

services:
  frontend:
    container_name: react-app
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules 
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_TASK_SERVICE_URL
      - VITE_ASK_AI_SERVICE_URL
      - VITE_COGNITO_REGION
      - VITE_COGNITO_POOL_ID
      - VITE_COGNITO_CLIENT_ID
    depends_on:
      - task_service
    command: npm run dev -- --host
  task_service:
    build: ./task_service
    ports:
      - "8000:8000"
    volumes:
      - ./task_service:/app  
    environment:
      - PYTHONUNBUFFERED=1
      - MONGO_URI
      - AUTH_SERVICE_URL

    depends_on:
      - mongodb
      - auth_service
    restart: always
  auth_service:
    build: ./auth_service
    ports:
      - "8001:8001"
    volumes:
      - ./auth_service:/app
    environment:
      - PYTHONUNBUFFERED=1
      - VITE_COGNITO_REGION
      - VITE_COGNITO_POOL_ID
      - VITE_COGNITO_CLIENT_ID
    depends_on:
      - mongodb
    restart: always
  ask_ai:
    build: ./ask_ai
    ports:
      - "8002:8000"  
    volumes:
      - ./ask_ai:/app  
    environment:
      - PYTHONUNBUFFERED=1
      - OPENAI_API_KEY
      - AUTH_SERVICE_URL
    depends_on:
      - auth_service
      - task_service
    restart: always
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      

volumes:
  mongodb_data: